# Generated by Django 3.2 on 2021-04-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='gallery/users')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
